---
- name: get external vars
  set_fact:
    ckan_db_server: "{{ CKAN_DB_SERVER|default('') }}"
    redis_server: "{{ REDIS_SERVER|default('') }}"
    solr_server: "{{ SOLR_SERVER|default('') }}"
    pycsw_db_server: "{{ PYCSW_DB_SERVER|default('') }}"

- name: Config db_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*db_server\s*=).*$' replace='\1 {{ckan_db_server}}'
  when: ckan_db_server != ""

- name: Config redis_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*ckan\.harvest\.mq\.hostname\s*=).*$' replace='\1 {{redis_server}}'
  when: redis_server != ""

- name: Config solr_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*solr_server\s*=).*$' replace='\1 {{solr_server}}'
  when: solr_server != ""

- name: Config pycsw_db_server in pycsw config files
  replace: dest={{ item }} regexp='(\s*db_server\s*=).*$' replace='\1 {{pycsw_db_server}}'
  when: pycsw_db_server != ""
  with_items:
    - /etc/ckan/pycsw-all.cfg
    - /etc/ckan/pycsw-collection.cfg
