---
- name: Create a table to indicate db init is in process
  shell: PGPASSWORD={{db_pass}} psql -h {{db_server}} -U{{db_user}} -d {{db_database}} -c "CREATE TABLE ckan_db_ini_start (ignore_this_table char(1));"
  register: ckan_install_reg
  failed_when: ckan_install_reg.rc != 0 and ("already exists" not in ckan_install_reg.stderr)
  changed_when: ckan_install_reg.rc == 0
  ignore_errors: True

- name: Initialize ckan db
  command: ckan db init
  register: ckan_initialize_reg
  ignore_errors: True
  when: ckan_install_reg.changed
  changed_when: ckan_initialize_reg.rc == 0 and ("SUCCESS" in ckan_initialize_reg.stdout)

- name: Create a table to indicate db init is done
  shell: PGPASSWORD={{db_pass}} psql -h {{db_server}} -U{{db_user}} -d {{db_database}} -c "CREATE TABLE ckan_db_ini_done (ignore_this_table char(1));"
  when: ckan_install_reg.changed

- name: Initialize ckan report db
  command: ckan --plugin=ckanext-report report initdb
  ignore_errors: True
  when: ckan_install_reg.changed and ckan_initialize_reg.changed

- name: Initialize pycsw db
  command: chdir=/usr/lib/ckan/bin/ ./pycsw-ckan.py -c setup_db -f /etc/ckan/pycsw-all.cfg
  ignore_errors: True
  when: ckan_install_reg.changed and ckan_initialize_reg.changed

