---
# The Network Time Protocol is used to manage the system clock over a network
# If every system on a network reliably reports the same time, then it is much easier to correlate log messages in case of an attack

- name: be sure ntp is installed
  apt: name=ntp state=installed
  tags:
    - ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes
  tags:
    - ntp
    - AU-8
