# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes

# SERVICE MODULE WILL NOT WORK (checked Ansible versions till 2.3.1)
# `service php7.0-fpm restart` itself will not start `php7.0-fpm` if it's not running
- name: php7.0-fpm status
  command: /etc/init.d/php7.0-fpm status
  register: php_fpm_status
  tags: skip_ansible_lint
  ignore_errors: true

- name: Start php7.0-fpm
  command: /etc/init.d/php7.0-fpm start
  when: '"is not running" in php_fpm_status.stdout'
  tags: skip_ansible_lint
  notify: restart nginx

- name: ReStart php7.0-fpm
  command: /etc/init.d/php7.0-fpm restart
  when: '"is running" in php_fpm_status.stdout'
  tags: skip_ansible_lint
  notify: restart nginx
