---
- name: get db credentials
  vars:
    production_ini: "/etc/ckan/production.ini"
    section: "app:main"
  set_fact: "{{item}}={{ lookup('ini', '{{item}} section={{section}} file={{production_ini}}') }}"
  with_items:
    - db_user
    - db_pass
    - db_server
    - db_database

- assert:
    that:
      - db_user != "" and db_pass != "" and db_server != "" and db_database != ""
