---
- name: get db credentials
  vars:
    production_ini: "/etc/ckan/production.ini"
    section: "app:main"

  set_fact: "{{item}}={{ lookup('ini', '{{item}} section={{section}} file={{production_ini}}') }}"
  with_items:
    - db_user
    - db_pass
    - db_server
    - db_database
    - datastore_user
    - datastore_pass
    - datastore_ro_user
    - datastore_ro_pass
    - datastore_server
    - datastore_database

- assert: { that: "{{ item }} != '' " }
  with_items:
    - db_user
    - db_pass
    - db_server
    - db_database
    - datastore_user
    - datastore_pass
    - datastore_ro_user
    - datastore_ro_pass
    - datastore_server
    - datastore_database
