---
# role url
url_readonly: "{{ urls_public.catalog }}"
url_writable: placeholder

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

# other
REDIS_SERVER: "localhost"
SOLR_SERVER: placeholder
env: local

# secrets
who_ini_secret: "{{ vault_who_ini_secret }}"
ckan_instance_secret: "{{ vault_ckan_instance_secret }}"
ckan_instance_uuid: "{{ vault_ckan_instance_secret }}"

# db credentials
CKAN_DB_SERVER: placeholder 
PYCSW_DB_SERVER: placeholder
catalog_db_user: placeholder
catalog_db_pass: placeholder
catalog_db_name: placeholder
catalog_pycsw_db_name: placeholder
