---
- name: Install CKAN Stack
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars:
      app_type: catalog

  ## tags used:
  ## built-in: always
  ## frontend, harvester, db, db-install, db-setup, db-init, solr, pycsw
  ## redis, fgdc2iso, cron
  ## sample usage: ansible-playbook ansibe/catalog.yml --tags "harvester" --skip-tags "solr,apache"
  roles:
    - {role: software/ubuntu/common, tags: ['always']}
    - {role: software/common/misc, tags: ['ami-fix', 'misc'] }
    - {role: software/common/ansible-postfix, tags: ['ami-fix', 'postfix'] }
    - {role: software/common/secops-ssh, tags: ['bsp', 'secops'] }
    - {role: software/common/trendmicro, tags: ['bsp', 'trendmicro'] }
    - {role: software/ckan/common, tags: ['frontend', 'harvester']}
    - {role: monitoring/fluentd/kernel, tags: ['bsp', 'fluentd'] }
    - {role: monitoring/fluentd/limits, tags: ['bsp', 'fluentd'] }
    - {role: monitoring/fluentd/td-agent, tags: ['bsp', 'fluentd'] }
    - {role: software/ckan/apache, tags: ['frontend', 'apache']}
    - {role: software/ckan/postgresql, tags: ['frontend', 'harvester', 'db', 'db-install']}
    - {role: software/ckan/solr, tags: ['frontend', 'harvester', 'solr']}

    - {role: software/catalog/ckan-app, tags: ['frontend', 'harvester', 'deploy']}
    - {role: software/catalog/ckan-db-setup, tags: ['frontend', 'harvester', 'db', 'db-setup']}
    - {role: software/catalog/ckan-db-init, tags: ['frontend', 'harvester', 'db', 'db-init']}

    - {role: software/catalog/harvest, tags: ['harvester']}

    - {role: software/catalog/pycsw-app, tags: ['frontend', 'harvester', 'pycsw']}
    - {role: software/catalog/pycsw-db-setup, tags: ['frontend', 'harvester', 'pycsw','db', 'db-setup']}
    - {role: software/catalog/pycsw-db-init, tags: ['frontend', 'harvester', 'pycsw','db', 'db-init']}

    - {role: software/ckan/saml2, tags: ['frontend', 'harvester', 'saml2']}

    - {role: software/ckan/security-fix, tags: ['frontend', 'harvester', 'pycsw']}

    - {role: software/ckan/fix-ckan-tracking, tags: ['frontend']}

    - {role: software/ec2/ec2-catalog, tags: ['frontend', 'harvester']}
    - {role: software/common/datagov-deploy-rollback, tags: ['deploy-rollback']}
