---
- name: Install EFK nginx proxy
  hosts: efk_nginx
  become: yes
  become_method: sudo
  remote_user: ubuntu

  roles:
  - role: geerlingguy.nginx
  - role: software/common/nginx-fixes
  - role: monitoring/efk-nginx
