---
- name: Install ElasticSearch
  hosts: elasticsearch
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'


- name: Install ElasticSearch
  hosts: elasticsearch
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
    - geerlingguy.java
    - { role: ansible.elasticsearch,
    es_config: {
        network.host: 0.0.0.0,
        network.publish_host: 0.0.0.0,
        }
    }

  vars:
    es_version: 5.6.1
    es_instance_name: "node1"
    es_java_install: false
    es_data_dirs: "/data"
    java_packages: openjdk-8-jdk
