---

- name: Install Nginx and configure it as a webproxy
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - role: software/catalog/nginx
    nginx_http_params:
      - sendfile "on"
      - access_log "/var/log/nginx/access.log"
      - error_log "/var/log/nginx/error.log"
    nginx_sites:
      default:
        - listen 80
        - location / { proxy_pass http://data.gov; }

    nginx_configs:
      proxy:
        - proxy_set_header X-Real-IP  $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
