---
# Global vars
# THESE ARE NOT DEFAULTS, THESE VARS OVERRIDE INVENTORY group_vars/*  !!!
# https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Nginx
nginx_remove_default_vhost: true

# PHP-FPM
php_enable_php_fpm: true
php_webserver_daemon: nginx

# new python version
python_version_number: 2.7.10
python_version_name: Python-{{ python_version_number }}
python_version_url: https://www.python.org/ftp/python/{{ python_version_number}}/{{ python_version_name }}.tgz
python_version_directory: /usr/local/lib/python{{ python_version_number }}/

# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false

# PHP
php_memory_limit: 512M
php_expose_php: 0
php_fpm_pm_max_children: 200
php_fpm_pm_start_servers: 15
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 20
php_fpm_request_terminate_timeout: 30s
php_opcache_conf_filename: "10-opcache.ini"
