--- # Additinal php configs

- name: Enable HTTPOnly cookie for sessionID
  lineinfile:
    dest: "/etc/php/7.0/fpm/php.ini"
    regexp: '^session.cookie_httponly'
    line: 'session.cookie_httponly = On'

- name: Enable cookie_secure for sessionID
  lineinfile:
    dest: "/etc/php/7.0/fpm/php.ini"
    regexp: '^session.cookie_secure'
    line: 'session.cookie_secure = On'

- name: Configure php-fpm pool
  lineinfile:
    dest: "/etc/php/7.0/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^.?request_terminate_timeout.?=.+$"
      line: "request_terminate_timeout={{ php_fpm_request_terminate_timeout }}"

- name: Set default php-cli to 7.0
  file:
    src: /usr/bin/php7.0
    dest: /usr/bin/php
    state: link
