
- name: restart supervisord
  service:
    name: supervisor
    state: restarted
    enabled: yes

- name: update supervisorctl
  supervisorctl:
    name: jekyll
    state: restarted
    config: /etc/supervisord.conf
