--- # CRM repo deployment & composer install

- name: Check whether new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p

- name: Create rollback code
  command: mv "{{ project_source_new_code_path }}" "{{ project_source_rollback_path }}"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Symlink current dir with rollback code
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ current_source_symlink }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Remove new code
  file: path="{{ project_source_new_code_path }}" state=absent

- name: Clone project files
  git:
    repo: "{{ project_git_repo }}"
    dest: "{{ project_source_new_code_path }}"
    version: "{{ project_git_version }}"
    force: true

- name: Composer install CRM
  composer:
    command: install
    arguments: "--ansi --no-dev --no-interaction --optimize-autoloader --no-scripts"
    working_dir: "{{ project_source_new_code_path }}"
  environment:
        COMPOSER_DISCARD_CHANGES: "true"

- name: Copying index.php
  template:
    src: "index.php"
    dest: "{{ project_source_new_code_path }}/index.php"

- name: Ensuring config directory exists
  file:
    path: "{{ project_source_new_code_path }}/application/config/{{ web_app_env }}"
    state: directory

- name: Copying config files
  template:
    src: "{{ item }}"
    dest: "{{ project_source_new_code_path }}/application/config/{{ web_app_env }}/{{ item | basename }}"
  with_fileglob:
    - ../templates/config/*.php

- name: Copying SAML config files
  template:
    src: "{{ item }}"
    dest: "{{ project_source_new_code_path }}/vendor/simplesamlphp/simplesamlphp/config/{{ item | basename }}"
  with_fileglob:
    - ../templates/saml/config/*.php

- name: Copying SAML metadata files
  template:
    src: "saml/metadata/{{ saml2_idp_entry }}/saml20-idp-remote.php"
    dest: "{{ project_source_new_code_path }}/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php"

- name: Fixing SAML (removing nameIdPolicy)
  replace:
    dest: "{{ project_source_new_code_path }}/vendor/simplesamlphp/saml2/src/SAML2/AuthnRequest.php"
    regexp: '\$root->appendChild\(\$nameIdPolicy\);'
    replace: '//$root->appendChild($nameIdPolicy) ;'

- name: Fixing SAML (replacing saml2-acs.php)
  replace:
    dest: "{{ project_source_new_code_path }}/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php"
    regexp: '\$msgStr = base64_encode\(\$msgStr\);'
    replace: '
        if (0 === stripos($_SERVER["REQUEST_URI"], "/crm")){
                $msgStr = str_replace(".gov/simple",".gov/crm/simple", $msgStr);
        }
        $msgStr = base64_encode(str_replace("simplesaml/module.php/saml/sp/saml2-acs.php/max","auth/acs",$msgStr));'

- name: Symlink current dir with new code
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ current_source_symlink }}"
    state: link
