--- # crm Web AMI

#- name: Initial prechecks
#  hosts: crm-web
#  remote_user: ubuntu
#
#  roles:
#  - { role: crm-sudo-0-precheck, tags: [precheck] }

- name: Provisioning Web AMI
  hosts: crm-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - software/common/die-no-tags
  - { role: software/common/misc, tags: [provision, misc] }
  - { role: software/common/php-common, tags: [provision] }
  - { role: geerlingguy.git, tags: [provision] }
  - { role: geerlingguy.nginx, tags: [provision] }
  - { role: software/common/nginx-fixes, tags: [provision] }
  - { role: geerlingguy.php, tags: [php, provision] }
  - { role: geerlingguy.php-mysql, tags: [php, php-mysql, provision] }
  - { role: geerlingguy.php-memcached, tags: [php, php-memcached, provision] }
  - { role: geerlingguy.composer, tags: [php, provision] }
  - { role: chusiang.vim-and-vi-mode, tags: [provision, vim] }
  - { role: software/crm/crm-sudo-2-init, tags: [provision, deploy, deploy-rollback] }
  - { role: software/common/secops-ssh, tags: [provision, secops, prod] }
  - { role: software/common/trendmicro, tags: [provision, trendmicro, prod] }
  - { role: software/common/ansible-postfix, tags: [provision, postfix, prod] }
  - { role: monitoring/fluentd/kernel, tags: [frontend, harvester, fluentd, prod] }
  - { role: monitoring/fluentd/limits, tags: [frontend, harvester, fluentd, prod] }
  - { role: monitoring/fluentd/td-agent, tags: [frontend, harvester, fluentd, prod] }


- name: Deploying crm
  hosts: crm-web
  remote_user: ubuntu

  roles:
  - { role: software/crm/crm-deploy, tags: [provision, deploy] }
  - { role: software/common/datagov-deploy-rollback, tags: [deploy-rollback] }


- name: Cleanup
  hosts: crm-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - { role: software/common/php-fixes, tags: [php, provision, deploy] }
  - { role: software/crm/crm-sudo-3-cleanup, tags: [provision, deploy, deploy-rollback] }

- name: CRM Migration
  hosts: crm-web
  remote_user: ubuntu

  roles:
  - { role: software/crm/crm-migrations, tags: [provision, deploy, migrate] }
