---

- name: Install ElasticSearch
  hosts: elasticsearch
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
  - ANXS.apt
  - geerlingguy.java
  - geerlingguy.elasticsearch

- name: Install Kibana
  hosts: kibana
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
  - geerlingguy.kibana

- name: Install EFK nginx proxy
  hosts: efk_nginx
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
  - role: geerlingguy.nginx
  - role: software/common/nginx-fixes
  - role: monitoring/efk-nginx

- name: Install Elastalert
  hosts: elasticsearch
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
    - role: ANXS.build-essential
    - role: teampants.elastalert
    - role: monitoring/elastalert
