---

- name: Remove elastalert rules
  file:
    path: "{{ elastalert_rules_dir }}"
    state: absent

- name: Create elastalert rules directory
  file:
    path: "{{ elastalert_rules_dir }}"
    state: directory

- name: Copy elastalert rules
  template:
    src: "{{ item }}"
    dest: "{{ elastalert_rules_dir }}/{{ item | basename | splitext | first }}"
  with_fileglob:
    - "../templates/*-rule.yml.j2"
  notify:
    - restart elastalert

- name: Set elastalert ownership
  file:
    path: "{{ item }}"
    owner: elastalert
    group: elastalert
    state: directory
    recurse: yes
  with_items:
    - /opt/elastalert
    - /etc/elastalert
