---
- name: Check s3cmd is present in pip
  pip: name=s3cmd state=present

- name: install gemset
  command: bash -lc "{{ item }}"
  with_items:
    - rvm use 2.3.0@{{gemset}} --create
    - rvm use 2.3.0@{{gemset}} && gem install jekyll specific_install
    - rvm use 2.3.0@{{gemset}} && gem uninstall jekyll-rebuilder
    - rvm use 2.3.0@{{gemset}} && gem specific_install https://github.com/GSA/jekyll-rebuilder
  tags: skip_ansible_lint


- name: get code
  git: repo={{item.repo}} dest=/root/{{item.name}} version={{item.branch|default('master')}}
  with_items: "{{jekyll_apps}}"

- include: supervisor.yml

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - root/.s3cfg

- name: copy template files
  template: src=templates/{{item}}.j2 dest=/{{item}}
  with_items:
    - etc/apache2/sites-enabled/jekyll.conf

- name: use command before buggy apache2_module is fixed
  command: a2enmod {{ item }}
  with_items:
    - proxy
    - proxy_http
  tags: skip_ansible_lint

- name: restart apache
  service: name=apache2 state=restarted
