--- # CRM prerequisites

- name: Copying SSL certs
  template:
    src: "web_{{ item }}"
    dest: "/etc/ssl/{{ item }}"
  with_items:
    - cert.pem
    - key.pem

- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf"
    dest: "/etc/nginx/sites-enabled/crm.nginx.conf"
#  notify:
#      - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Copy SAML crt
  template:
    src: "mycert.pem"
    dest: "{{ saml_sp_cert_path }}"
    mode: 0644

- name: Copy SAML key
  template:
    src: "mykey.pem"
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644

- name: Installing required packages
  package: name={{ item }} state=installed
  with_items:
    - mariadb-client-5.5
    - php7.0-zip
    - nginx-extras

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent
