---


- name: get external vars
  set_fact:
    ckan_db_server: "{{ CKAN_DB_SERVER|default('') }}"
    datastore_db_server: "{{ DATASTORE_DB_SERVER|default('') }}"
    solr_server: "{{ SOLR_SERVER|default('') }}"
    bucket_name: "{{ BUCKET_NAME|default('') }}"

- name: get optional external vars
  set_fact:
    bucket_prefix: "{{ BUCKET_PREFIX }}"
  when: BUCKET_PREFIX is defined

- name: Config db_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*db_server\s*=).*$' replace='\1 {{ckan_db_server}}'
  when: ckan_db_server != ""

- name: Config db_server in datapusher_settings.py
  replace: dest=/etc/ckan/datapusher_settings.py regexp='(\s*db_server\s*=).*$' replace='\1 "{{ckan_db_server}}"'
  when: datastore_db_server != ""

- name: Config datastore_db_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*datastore_server\s*=).*$' replace='\1 {{datastore_db_server}}'
  when: datastore_db_server != ""

- name: Config solr_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*solr_server\s*=).*$' replace='\1 {{solr_server}}'
  when: solr_server != ""

- name: Config bucket in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*ckanext\.s3filestore\.aws_bucket_name\s*=).*$' replace='\1 {{bucket_name}}'
  when: bucket_name != ""

- name: Config bucket prefix in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*ckanext\.s3filestore\.aws_storage_path\s*=).*$' replace='\1 {{bucket_prefix}}'
  when:
    - bucket_prefix is defined
